# Generated by Django 6.0.5 on 2026-06-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_filename',
            field=models.CharField(default='default.avif', help_text='Filename of the image in assets folder', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
