# Generated by Django 6.0.5 on 2026-06-02 12:51

from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()
    # Ensure you don't create duplicates if it already exists
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin', 'admin@example.com', 'yourpassword123')

class Migration(migrations.Migration):
    dependencies = [('core', '0001_initial')] # Make sure this matches your dependency
    operations = [migrations.RunPython(create_superuser)]