# Generated by Django 6.0.5 on 2026-06-02 12:51

from django.db import migrations
from django.contrib.auth import get_user_model

def reset_password(apps, schema_editor):
    User = get_user_model()
    # Use get_or_create to prevent DoesNotExist errors
    user, created = User.objects.get_or_create(username='admin')
    
    # Now you can safely set the password
    user.set_password('YourNewSecurePassword123!')
    user.is_superuser = True
    user.is_staff = True
    user.save()

class Migration(migrations.Migration):
    dependencies = [('core', '0001_initial')] 
    operations = [migrations.RunPython(reset_password)]