# Generated by Django 6.0.5 on 2026-06-02 12:51

from django.db import migrations
from django.contrib.auth import get_user_model

def reset_password(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [('core', '0001_initial')] 
    operations = [migrations.RunPython(reset_password)]