# Generated by Django 6.0.5 on 2026-06-03 07:21

from django.db import migrations
from django.utils.text import slugify  # <--- Add this import

def add_all_products(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    Category = apps.get_model('core', 'Category')
    ProductImage = apps.get_model('core', 'ProductImage')

    cat, _ = Category.objects.get_or_create(name="Apparel")

    product_data = [...] # (Keep your data list)

    for item in product_data:
        # Create product with an explicit unique slug
        product = Product.objects.create(
            category=cat,
            name=item['name'],
            slug=slugify(item['name']), # <--- Manually set the slug here
            description=item['desc'],
            price=item['price'],
            stock=item['stock']
        )
        
        ProductImage.objects.create(
            product=product,
            image_filename=item['filename'],
            alt_text=f"{item['name']} product view"
        )

class Migration(migrations.Migration):
    # Ensure this points to the migration that added 'image_filename' (Step 2)
    dependencies = [('core', '0002_remove_productimage_image_url_and_more')] 
    operations = [migrations.RunPython(add_all_products)]
