# Generated by Django 6.0.5 on 2026-06-02 13:00

from django.db import migrations
from django.utils.text import slugify  # <--- YOU MUST ADD THIS IMPORT

def add_initial_products(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    Product = apps.get_model('core', 'Product')
    ProductImage = apps.get_model('core', 'ProductImage')

    # 1. Create the category
    category, _ = Category.objects.get_or_create(name="Apparel")

    # 2. Define your data
    products_data = [
        {"name": "Black Slim Jeans", "price": 1200, "filename": "black_jeans.avif", "desc": "Premium quality slim fit."},
        {"name": "Black T-Shirt", "price": 500, "filename": "black_t-shirts.avif", "desc": "Cotton crew neck."},
        {"name": "Checkered Shirt", "price": 850, "filename": "chex_shirts.avif", "desc": "Classic checkered pattern."},
        {"name": "White Hoodie Combo", "price": 1500, "filename": "complete_combo.avif", "desc": "Modern white hoodie."},
        {"name": "Denim Collection", "price": 2000, "filename": "denim_collection.avif", "desc": "Exclusive denim variety."},
        {"name": "Pink Jacket", "price": 1800, "filename": "jacket.avif", "desc": "Elegant double-breasted jacket."},
        {"name": "Premium Jeans", "price": 1400, "filename": "premium_jeans.avif", "desc": "High-grade denim fabric."},
        {"name": "Premium T-Shirt", "price": 600, "filename": "premium_t-shirts.avif", "desc": "Soft touch premium cotton."},
        {"name": "Casual Shirts", "price": 900, "filename": "shirts.avif", "desc": "Lightweight casual daily wear."},
        {"name": "T-Shirt Set", "price": 700, "filename": "t-shirts.avif", "desc": "Versatile multi-color set."},
    ]

    # 3. Save to database
    for p in products_data:
        # Check if product exists to prevent UNIQUE constraint errors if you re-run
        product, created = Product.objects.get_or_create(
            name=p['name'],
            defaults={
                'category': category,
                'price': p['price'],
                'description': p['desc'],
                'slug': slugify(f"{p['name']}-{p['filename']}")
            }
        )
        
        # Only create the image entry if the product was newly created
        if created:
            ProductImage.objects.create(
                product=product,
                image_url=p['filename'], 
                alt_text=p['name']
            )

class Migration(migrations.Migration):
    dependencies = [('core', '0001_initial')] 
    operations = [migrations.RunPython(add_initial_products)]