# Generated by Django 6.0.5 on 2026-06-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_superuser'),
        ('core', '0003_add_initial_products'),
    ]

    operations = [
    ]
