# Generated by Django 6.0.5 on 2026-06-02 13:17

from django.db import migrations
from django.contrib.auth import get_user_model

def reset_password(apps, schema_editor):
    User = get_user_model()
    # Find the 'admin' user and set a new password
    try:
        user = User.objects.get(username='admin')
        user.set_password('NewSecurePassword123!') # CHANGE THIS to your desired password
        user.save()
    except User.DoesNotExist:
        pass

class Migration(migrations.Migration):
    # Update this to match the name of the file created before this one
    dependencies = [('core', '0003_add_initial_products')] 
    operations = [migrations.RunPython(reset_password)]