# Generated by Django 6.0.5 on 2026-06-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_0002_create_superuser_0003_add_initial_products'),
        ('core', '0005_reset_password'),
    ]

    operations = [
    ]
